import router from "express";
const streamRouter = router();
import { createStream } from "../controllers/Stream";
import { getpreviousStreams } from "../controllers/Stream";
import { verifyToken } from "../middleware/middleware"; 
import { updateStreamStatus } from "../controllers/Stream";
import { fetchStreams } from "../controllers/Stream";
import { getStreamForViewer } from "../controllers/Stream";
import { getViewerCount } from "../controllers/Stream";
import { getMessages } from "../controllers/Stream";
streamRouter.post("/create", verifyToken,createStream);
streamRouter.get("/previousStreams", verifyToken,getpreviousStreams);
streamRouter.post("/updateStatus", verifyToken,updateStreamStatus);
streamRouter.get("/allStreams", verifyToken,fetchStreams);
streamRouter.get("/:id", verifyToken,getStreamForViewer);
streamRouter.get("/viewers/count/:id", verifyToken,getViewerCount);
streamRouter.get("/messages/:id", verifyToken,getMessages);
export default streamRouter;